openapi: 3.0.3
info:
    title: Task Service
    description: Service for managing tasks
    version: "1.0"
servers:
    - url: http://0.0.0.0:8000
paths:
    /auth/login:
        post:
            tags:
                - auth
            summary: login auth
            description: Login to the system
            operationId: auth#login
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LoginRequestBody'
                        example:
                            password: Eaque tenetur.
                            username: Id eos repudiandae voluptates nihil repellat impedit.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                token: Illo non quibusdam magni.
                "401":
                    description: 'login_failed: User not found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AuthFlowFailed'
                            example:
                                message: Omnis mollitia.
                                name: Mollitia odio incidunt ut ducimus.
    /auth/register:
        post:
            tags:
                - auth
            summary: register auth
            description: Register a new user
            operationId: auth#register
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LoginRequestBody'
                        example:
                            password: Rerum dolor.
                            username: Consequatur aut.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                token: Molestias est qui.
                "400":
                    description: 'register_failed: Username already exists'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AuthFlowFailed'
                            example:
                                message: Quis qui non.
                                name: Molestias est voluptas et.
    /tasks:
        get:
            tags:
                - task
            summary: list task
            description: List all tasks
            operationId: task#list
            parameters:
                - name: limit
                  in: query
                  description: Maximum number of tasks to return
                  allowEmptyValue: true
                  schema:
                    type: integer
                    description: Maximum number of tasks to return
                    default: 20
                    example: 100
                  example: 100
                - name: offset
                  in: query
                  description: Offset into the list of tasks to start at
                  allowEmptyValue: true
                  schema:
                    type: integer
                    description: Offset into the list of tasks to start at
                    default: 0
                    example: 0
                  example: 0
                - name: name
                  in: query
                  description: Filter by name
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Filter by name
                    default: ""
                    example: task1
                  example: task1
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ListResponseBody'
                            example:
                                tasks:
                                    - createdAt: Cupiditate autem quibusdam.
                                      createdBy: Soluta unde quibusdam aut et.
                                      description: Voluptate dolores quas et ex.
                                      done: true
                                      doneAt: Molestiae sed vitae aperiam eaque qui.
                                      doneBy: Nihil ipsam sunt autem accusamus beatae eaque.
                                      id: 1602291338
                                      name: Tempore et id labore ipsa ullam.
                                    - createdAt: Cupiditate autem quibusdam.
                                      createdBy: Soluta unde quibusdam aut et.
                                      description: Voluptate dolores quas et ex.
                                      done: true
                                      doneAt: Molestiae sed vitae aperiam eaque qui.
                                      doneBy: Nihil ipsam sunt autem accusamus beatae eaque.
                                      id: 1602291338
                                      name: Tempore et id labore ipsa ullam.
                "401":
                    description: 'token_verification_failed: Unauthorized response.'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AuthFailed'
                            example:
                                message: Optio ut aut voluptatum eaque et harum.
            security:
                - jwt_header_Authorization:
                    - api:read
        post:
            tags:
                - task
            summary: create task
            description: Create a task
            operationId: task#create
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateRequestBody'
                        example:
                            created_by: Architecto quaerat reprehenderit distinctio ut incidunt.
                            description: Doloremque dolore in maxime quidem.
                            id: 85019628
                            name: Nesciunt suscipit vel et blanditiis.
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ShowResponseBody'
                            example:
                                task:
                                    createdAt: Cupiditate autem quibusdam.
                                    createdBy: Soluta unde quibusdam aut et.
                                    description: Voluptate dolores quas et ex.
                                    done: true
                                    doneAt: Molestiae sed vitae aperiam eaque qui.
                                    doneBy: Nihil ipsam sunt autem accusamus beatae eaque.
                                    id: 1602291338
                                    name: Tempore et id labore ipsa ullam.
                "401":
                    description: 'token_verification_failed: Unauthorized response.'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AuthFailed'
                            example:
                                message: Accusamus odio.
            security:
                - jwt_header_Authorization:
                    - api:read
    /tasks/{id}:
        delete:
            tags:
                - task
            summary: delete task
            description: Delete a task
            operationId: task#delete
            parameters:
                - name: id
                  in: path
                  description: ID of task to delete
                  required: true
                  schema:
                    type: integer
                    description: ID of task to delete
                    example: 3888403916
                  example: 969315955
            responses:
                "200":
                    description: OK response.
                "401":
                    description: 'token_verification_failed: Unauthorized response.'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AuthFailed'
                            example:
                                message: Itaque qui et est voluptas eum.
            security:
                - jwt_header_Authorization:
                    - api:read
        get:
            tags:
                - task
            summary: show task
            description: Show a task
            operationId: task#show
            parameters:
                - name: id
                  in: path
                  description: ID of task to show
                  required: true
                  schema:
                    type: integer
                    description: ID of task to show
                    example: 2754367074
                  example: 2986115634
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ShowResponseBody'
                            example:
                                task:
                                    createdAt: Cupiditate autem quibusdam.
                                    createdBy: Soluta unde quibusdam aut et.
                                    description: Voluptate dolores quas et ex.
                                    done: true
                                    doneAt: Molestiae sed vitae aperiam eaque qui.
                                    doneBy: Nihil ipsam sunt autem accusamus beatae eaque.
                                    id: 1602291338
                                    name: Tempore et id labore ipsa ullam.
                "401":
                    description: 'token_verification_failed: Unauthorized response.'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AuthFailed'
                            example:
                                message: Sed quis.
                "404":
                    description: 'task_not_found: task not found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AuthFlowFailed'
                            example:
                                message: Sit ut numquam repellendus vel.
                                name: Provident tempora ad non accusamus sit delectus.
            security:
                - jwt_header_Authorization:
                    - api:read
        put:
            tags:
                - task
            summary: update task
            description: Update a task
            operationId: task#update
            parameters:
                - name: id
                  in: path
                  description: ID of task to update
                  required: true
                  schema:
                    type: integer
                    description: ID of task to update
                    example: 15551498
                  example: 1649374883
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateRequestBody'
                        example:
                            description: Pariatur eos ut.
                            name: Aut quos culpa voluptatum repellat minus ratione.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ShowResponseBody'
                            example:
                                task:
                                    createdAt: Cupiditate autem quibusdam.
                                    createdBy: Soluta unde quibusdam aut et.
                                    description: Voluptate dolores quas et ex.
                                    done: true
                                    doneAt: Molestiae sed vitae aperiam eaque qui.
                                    doneBy: Nihil ipsam sunt autem accusamus beatae eaque.
                                    id: 1602291338
                                    name: Tempore et id labore ipsa ullam.
                "401":
                    description: 'token_verification_failed: Unauthorized response.'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AuthFailed'
                            example:
                                message: Dolorem fugiat quo quia quaerat.
                "404":
                    description: 'task_not_found: Task not found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AuthFlowFailed'
                            example:
                                message: Nulla odio neque itaque ea odio distinctio.
                                name: Sequi nihil.
            security:
                - jwt_header_Authorization:
                    - api:read
    /tasks/{id}/done:
        put:
            tags:
                - task
            summary: done task
            description: Mark a task as done
            operationId: task#done
            parameters:
                - name: id
                  in: path
                  description: ID of task to mark as done
                  required: true
                  schema:
                    type: integer
                    description: ID of task to mark as done
                    example: 50443062
                  example: 672706765
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/DoneRequestBody'
                        example:
                            done_by: Veritatis doloremque ad.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ShowResponseBody'
                            example:
                                task:
                                    createdAt: Cupiditate autem quibusdam.
                                    createdBy: Soluta unde quibusdam aut et.
                                    description: Voluptate dolores quas et ex.
                                    done: true
                                    doneAt: Molestiae sed vitae aperiam eaque qui.
                                    doneBy: Nihil ipsam sunt autem accusamus beatae eaque.
                                    id: 1602291338
                                    name: Tempore et id labore ipsa ullam.
                "401":
                    description: 'token_verification_failed: Unauthorized response.'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AuthFailed'
                            example:
                                message: Quisquam voluptas consequuntur dolorem libero.
            security:
                - jwt_header_Authorization:
                    - api:read
components:
    schemas:
        AuthFailed:
            type: object
            properties:
                message:
                    type: string
                    description: Error message
                    example: Enim possimus voluptatem alias qui inventore.
            example:
                message: Quis unde nihil ipsum sapiente dolores.
            required:
                - message
        AuthFlowFailed:
            type: object
            properties:
                message:
                    type: string
                    description: reason for failure
                    example: Quibusdam aut earum iste sit.
                name:
                    type: string
                    description: Name of the error
                    example: Velit dolorem totam a ea porro adipisci.
            description: User not found
            example:
                message: Quidem fugiat ullam accusantium rerum omnis.
                name: Ducimus soluta omnis mollitia repudiandae aliquid est.
            required:
                - message
                - name
        BackendStoredTask:
            type: object
            properties:
                createdAt:
                    type: string
                    description: When the todo was created in ISO format
                    example: Magnam aliquid molestiae ea fugit et nobis.
                createdBy:
                    type: string
                    description: Who created the todo
                    example: Accusamus ut voluptatum.
                description:
                    type: string
                    description: Description of the todo
                    example: Enim quia veritatis labore est aliquam.
                done:
                    type: boolean
                    description: Whether or not the todo is done
                    default: false
                    example: false
                doneAt:
                    type: string
                    description: When the todo was done in ISO format
                    default: ""
                    example: Possimus praesentium ea blanditiis voluptate tenetur tempore.
                doneBy:
                    type: string
                    description: Who did the todo
                    default: ""
                    example: Veniam nihil et.
                id:
                    type: integer
                    description: Unique ID
                    example: 4033005453
                name:
                    type: string
                    description: Name of the todo
                    example: Sed voluptatibus et praesentium tempore voluptatum qui.
            description: A task
            example:
                createdAt: Magni impedit sed qui libero repellat.
                createdBy: Quis voluptas est.
                description: Aut similique voluptatibus.
                done: true
                doneAt: Sint qui.
                doneBy: Quaerat occaecati expedita commodi.
                id: 3877584788
                name: Et consequatur.
            required:
                - id
                - name
                - description
                - done
                - createdAt
                - createdBy
        BackendStoredTaskCollection:
            type: array
            items:
                $ref: '#/components/schemas/BackendStoredTask'
            example:
                - createdAt: Cupiditate autem quibusdam.
                  createdBy: Soluta unde quibusdam aut et.
                  description: Voluptate dolores quas et ex.
                  done: true
                  doneAt: Molestiae sed vitae aperiam eaque qui.
                  doneBy: Nihil ipsam sunt autem accusamus beatae eaque.
                  id: 1602291338
                  name: Tempore et id labore ipsa ullam.
                - createdAt: Cupiditate autem quibusdam.
                  createdBy: Soluta unde quibusdam aut et.
                  description: Voluptate dolores quas et ex.
                  done: true
                  doneAt: Molestiae sed vitae aperiam eaque qui.
                  doneBy: Nihil ipsam sunt autem accusamus beatae eaque.
                  id: 1602291338
                  name: Tempore et id labore ipsa ullam.
                - createdAt: Cupiditate autem quibusdam.
                  createdBy: Soluta unde quibusdam aut et.
                  description: Voluptate dolores quas et ex.
                  done: true
                  doneAt: Molestiae sed vitae aperiam eaque qui.
                  doneBy: Nihil ipsam sunt autem accusamus beatae eaque.
                  id: 1602291338
                  name: Tempore et id labore ipsa ullam.
        CreateRequestBody:
            type: object
            properties:
                created_by:
                    type: string
                    description: Who created the task
                    example: Non doloribus occaecati sit sint deserunt quod.
                description:
                    type: string
                    description: Description of the task
                    example: Ab deleniti delectus sit repellat.
                id:
                    type: integer
                    description: ID of task to create
                    example: 3671769855
                name:
                    type: string
                    description: Name of the task
                    example: Quo est non corrupti in aut fuga.
            example:
                created_by: Dolores delectus.
                description: Reprehenderit rerum aut fuga quod id.
                id: 2276439016
                name: Iste consectetur a.
            required:
                - name
                - created_by
        DoneRequestBody:
            type: object
            properties:
                done_by:
                    type: string
                    description: Who did the task
                    example: Neque ut.
            example:
                done_by: Et officia est necessitatibus sed laboriosam corrupti.
            required:
                - done_by
        ListResponseBody:
            type: object
            properties:
                tasks:
                    $ref: '#/components/schemas/BackendStoredTaskCollection'
            example:
                tasks:
                    - createdAt: Cupiditate autem quibusdam.
                      createdBy: Soluta unde quibusdam aut et.
                      description: Voluptate dolores quas et ex.
                      done: true
                      doneAt: Molestiae sed vitae aperiam eaque qui.
                      doneBy: Nihil ipsam sunt autem accusamus beatae eaque.
                      id: 1602291338
                      name: Tempore et id labore ipsa ullam.
                    - createdAt: Cupiditate autem quibusdam.
                      createdBy: Soluta unde quibusdam aut et.
                      description: Voluptate dolores quas et ex.
                      done: true
                      doneAt: Molestiae sed vitae aperiam eaque qui.
                      doneBy: Nihil ipsam sunt autem accusamus beatae eaque.
                      id: 1602291338
                      name: Tempore et id labore ipsa ullam.
        LoginRequestBody:
            type: object
            properties:
                password:
                    type: string
                    description: Password to login with
                    example: Rerum molestiae iste.
                username:
                    type: string
                    description: Username to login with
                    example: Similique quo quas ut et.
            example:
                password: Et deleniti nisi et iusto odio.
                username: Nostrum vero debitis debitis consequatur qui.
            required:
                - username
                - password
        LoginResponseBody:
            type: object
            properties:
                token:
                    type: string
                    description: JWT token to use for authentication
                    example: Consequatur aut quasi architecto.
            example:
                token: Ut ullam quia voluptatem a molestiae.
            required:
                - token
        ShowResponseBody:
            type: object
            properties:
                task:
                    $ref: '#/components/schemas/BackendStoredTask'
            example:
                task:
                    createdAt: Cupiditate autem quibusdam.
                    createdBy: Soluta unde quibusdam aut et.
                    description: Voluptate dolores quas et ex.
                    done: true
                    doneAt: Molestiae sed vitae aperiam eaque qui.
                    doneBy: Nihil ipsam sunt autem accusamus beatae eaque.
                    id: 1602291338
                    name: Tempore et id labore ipsa ullam.
        UpdateRequestBody:
            type: object
            properties:
                description:
                    type: string
                    description: Description of the task
                    example: Exercitationem quo aut laboriosam ab.
                name:
                    type: string
                    description: Name of the task
                    example: Sint officiis et assumenda et veritatis.
            example:
                description: Numquam laborum sint qui error.
                name: Architecto et non exercitationem saepe voluptas incidunt.
    securitySchemes:
        jwt_header_Authorization:
            type: http
            description: JWT Authentication for the API
            scheme: bearer
tags:
    - name: auth
      description: The auth service manages authentication
    - name: task
      description: The task service manages task lists
